// Generated by CoffeeScript 1.6.2
(function() {
  var $, angle, root, rotate, save, set, trial;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  trial = 0;

  angle = 0;

  $ = function(id) {
    return document.getElementById(id);
  };

  document.ontouchmove = function(e) {
    return e.preventDefault();
  };

  root.init = function() {
    var right;

    set(trial);
    right = $("right");
    right.addEventListener("gesturechange", rotate, false);
    return right.addEventListener("gestureend", save, false);
  };

  save = function(e) {
    return angle += e.rotation;
  };

  set = function(i) {
    var deg, dir, image, r, _ref;

    _ref = trials[i], image = _ref.image, dir = _ref.dir, deg = _ref.deg;
    $("left").style.backgroundImage = "url(\"images/left/" + image + ".gif\")";
    r = $("right");
    r.style.backgroundImage = "url(\"images/" + dir + "/" + image + ".gif\")";
    r.style.webkitTransform = "rotate(" + deg + "deg)";
    return angle = deg;
  };

  rotate = function(e) {
    e.preventDefault();
    return $(this.id).style.webkitTransform = "rotate(" + (angle + e.rotation) + "deg)";
  };

  root.prev = function() {
    if (trial > 0) {
      return set(--trial);
    }
  };

  root.next = function() {
    if (trial === trials.length - 1) {
      return alert("Congratulations, you finished the task!");
    } else {
      return set(++trial);
    }
  };

}).call(this);
