// Generated by CoffeeScript 1.6.3
(function() {
  var $, apples, background, draw, drawApple, h, i, left, margin, region, reset, right, w, x, y, _i;

  margin = 30;

  w = 800;

  h = 800;

  apples = [];

  $ = function(select) {
    return document.querySelectorAll(select);
  };

  draw = SVG('canvas').size(800, 800);

  background = draw.rect(w, h).fill('#586e75');

  region = function(x, y) {
    return draw.rect(x, y).attr({
      fill: 'whitesmoke',
      rx: x * .15,
      ry: y * .10
    });
  };

  x = (w - margin) / 2;

  y = h * .85;

  left = region(x, y);

  right = region(x, y);

  right.move(x + margin, 0);

  drawApple = function(cx, cy) {
    var apple;
    apple = draw.image('images/apple.png', 50, 57).attr({
      "class": 'apple',
      cursor: '-webkit-grab'
    }).data('cx', cx).data('cy', cy).move(cx, cy).draggable();
    apples.push(apple);
    return apple;
  };

  for (i = _i = 0; _i <= 8; i = ++_i) {
    drawApple(i * 85 + margin, y + margin);
  }

  reset = function(e) {
    var apple, _j, _len, _results;
    _results = [];
    for (_j = 0, _len = apples.length; _j < _len; _j++) {
      apple = apples[_j];
      x = apple.data('cx');
      y = apple.data('cy');
      _results.push(apple.animate().move(x, y));
    }
    return _results;
  };

  redo.addEventListener("click", reset, false);

}).call(this);
